export const shopActionTypes = {
  SET_SHOP_ITEMS: "SET_SHOP_ITEMS",
  SET_DEFAULT_QUANTITY_DESIRED: "SET_DEFAULT_QUANTITY_DESIRED",
  SET_DEFAULT_CHECKED: "SET_DEFAULT_CHECKED",
  SET_DEFAULT_SOLD: "SET_DEFAULT_SOLD",
};
