export const cartActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  CHECKED_ITEM: "CHECKED_ITEM",
  CHECKED_ALL_ITEM: "CHECKED_ALL_ITEM",
  INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_QUANTITY",
  DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
};
