export const cartActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  ADD_ITEM_WITH_QUANTITY: "ADD_ITEM_WITH_QUANTITY",
  DELETE_ITEM: "DELETE_ITEM",
  DELETE_ALL_ITEM: "DELETE_ALL_ITEM",
  CHECKED_ITEM: "CHECKED_ITEM",
  CHECKED_ALL_ITEM: "CHECKED_ALL_ITEM",
  INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_QUANTITY",
  DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
  SET_DELIVERY_TYPE: "SET_DELIVERY_TYPE",
  SET_PAYMENT_TYPE: "SET_PAYMENT_TYPE",
  STATE_ITEM_TO_NEXT: "STATE_ITEM_TO_NEXT",
  FINISHED_TRANSACTION: "FINISHED_TRANSACTION",
};
